language: csharp
mono: none
dotnet: 2.1
branches:
  only:
    - master
script:
  - dotnet restore
deploy:
  provider: heroku
  api_key:
    secure: APXp6wq0InWaaLyTaFXd++uxwY2dR+AtJKlV7VnYiliLFtCaSBts1fcxs57V1gumgi1ALZW6vlreBZmKn3nSplzfzmpuSFNIunYOWX5R8mSOOQP4l9U2npwKMGDxwf4v0FhIkKscvMnQNOhBvPzCxaaKJzZN/iNSh97vAkYsEWkn4JA6i41xKHDfzZ9hAg7Vw0MoQ4SLZY+g1WDN5kkrR7vcu/EtgehLPTXljIgBzr7YtXujGaxXCusFV3P45hCpjPkpKnkDs/ORBSh3ylUwnQYeVncl4u2IdI5jB3pHcjZxFFKVSN9SEf82J3+FJR+QCADcYonEgT5yv9wuOo4ElIzjMqmhayNrcPB6GWEwbPkmaLH6TQaxaaj9lxGUAYnLCm/VOC4WsqmMv4JiokgE3x4iv99hdSLPe38zH/qH3uS+zSFb58QyitKiP/crzaZSszYcFYSadJB7JPF3N4Ap+1sNc5KnFijhToUbV/tbEbSa8gjmXZNRfDUezPxiInIkSq6L5+UWqOS32lAaq0xER/IGQXss/HuMtZWzg+RmNzsTuaLM4eNWOmYXvFLPHwD1chwTNCvVEkq7+ls9gH9BzyXeW16cU+WcFuAOV4tjIVDsB2XR8wjMtTr83W9W0WGJFNy1AjZPugm4gOQzpCcFG83c/Eo9eQTlb6xSOoyBVHc=
