language: csharp
mono: none
dotnet: 2.1
script:
  - dotnet restore
deploy:
  provider: heroku
  api_key:
    secure: rfF/tgpVilrd+lcVcBARXPsv7tzUtKSP8Ppvv+eWm1RwfnAJlGtpekyUqezvYaneyRIUSoXec2DuJZOerbTGG4E3YKd9ogq9PkudxTcUEQWFNR/RkPgGubAmHDZERrGGKonlwDX4MdUlkIraj4pXtoYapWiqA0mPSdBN+qSHPmiIHbdWeEh/xvKDYO3yMzsqS+svwLeWvUhB5Ool+u+syMjsuRt/vj0LmfgZKY5hI1ZzMLHmY5+ZBachKt+Q9hy/fhv4YBFXKW/dHkX1P5hziAI1i87Z3uqD1s0/bhHGEKsXLZN95cD5o3Xhb5lr1SNv1m+l6i6zX6sGs/I3jcLVs5mA7kp/ufR7KOO5XkBQ0oAu0wEw9ceC5ju6Fm466bqzfMbm8x/fy2ZPfBfDN9xmZnFlAT04yyhKsEV178MYb/ckLkkNLgkrctbsHDGYv/cc/I0/RKDz9ALQccjUSOCimqqf4EcyPY8A+Icqjb3K/S0EHBa51g8zfiSog/I2qyibGpP5+R5WwC3HDDXo3XKCgnQK6FOylcYRpQmGgGgeihBCwuZM/cZcgteWwzk7r5Wo/7RvdZThBSMpCXTxc6taIRiKSPCmxqXsim8N9DT5JRzAL7hqMaKH8tDTqB/t+nPhAYCnN8+ZqUZAJzZoWeXMeISOb+mADz8K2HXCFl14Gm0=
