language: csharp
mono: none
dotnet: 2.1
script:
  - dotnet restore
deploy:
  provider: heroku
  api_key:
    secure: tWzdudyLaPS0LuwNnlF6d9FG38nhXi7KsYwAke5qXa7jGazBkxxMs2tfNrebpBEas2Ik7t53IIgBg1rrXoCLdyuhXGOUWwEUnajrCP1ehzEP7Tav9V8Xyzvnxc+/WkrNotH4ncA9I5qSe1cPyRG9HWFNTaz7sK4v7OSiSxOpmQNhLjiDD8y8xrw0CwgCAUIneJkjgSHJo+Z/5teMJaMhf80BuUqVxuut4Ox+CYL+FCfR84ZkvPU1lC41wzqRdnr3i/q13P+/zgv5dWAJww0RivMp30Qi8IMVqjeyBS9b2/A5d6j0qSfdjDonKbFW6ULPHbbw19t6GShv83TEjRgmiuwS+GRN4vHeEvdQaIx65OFfY1Y1dqF4T+Y5sm9bfhK1bnbIsGeiob5f3nU0L6x0OsUqvDlIZBjmEoapaiyPPrANrqO1suIGImoyEu9MuHYrxqu1OCavwOc2tr3YPW1RH4WOq72bvVl1zffTHOqwalpZXpWDbZ8cu7HYbd4bLlOIrAaz057TK/jVd1RTx39cATGSb6H7+kdouA5nxUEKFmOIO048sxWuIaAGP3RzXjtEqG7YbbYE8TeVzKJV+vohRiAIHKvHXZRtdyE6eBqrtuVagphshbgPLGurdvK7QbhQ0CJ/KWO6kYSDIRrEqiJhr/FRWXmz4rYwTu7ihyzDQig=
